Trying to fix circular import
I get "1909ERROR: Failure: ImportError (cannot import name utils)" in
Python 2.7, and I believe it's because of this issue:

http://effbot.org/zone/import-confusion.htm

If in worm_features.py,
`from .. import utils` comes BEFORE the
`from . import events`, etc, we may have a problem I don't fully
understand.  So I'm putting the utils import line last to see if that
fixes it.